name: Deploy to EC2 on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Deploy to EC2
        run: |
          # Your deployment steps here
          # For example, you can use SSH to copy files to your EC2 instance and execute commands remotely.

      - name: Update Environment File
        run: echo "DEPLOYMENT_STATUS=success" >> $GITHUB_ENV

      - name: Deploy Complete
        run: echo "Deployment to EC2 is complete!"

      - name: Upload Environment File
        uses: actions/upload-artifact@v2
        with:
          name: environment
          path: $GITHUB_ENV
