name: Development and Production on Master Branch Push

on:
  push:
    branches:
      - master

jobs:
  deploy-development:
    name: Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Step 2 - Configure AWS credentials for Development
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

  deploy-production:
    runs-on: ubuntu-latest
    needs: [deploy-development]  # Assuming this is the job that needs to finish first
    if: github.ref != 'refs/heads/master'  # Add this condition to prevent execution on the master branch
    steps:
      - name: Step 1 - Configure AWS credentials for Deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Step 2 - Create CodeDeploy Deployment for Development
        id: deploy-development
        run: |
          aws deploy create-deployment \
            --application-name Git_Application \
            --deployment-group-name deployment_group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

      - name: Step 3 - Install and start Apache for Development
        run: |
          sudo apt-get -y update
          sudo apt-get install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2
